name: Enables Auto-merge on PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PRs
        run: gh pr merge --auto --squash --delete-branch --subject="$PR_TITLE" --body="$PR_URL $PR_CREATED_AT" "$PR_URL"
        env:
          PR_TITLE: ${{github.event.pull_request.title}}
          PR_CREATED_AT: ${{github.event.pull_request.created_at}}
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
